name: API Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install

      - name: Run Artillery tests
        run: |
          npx artillery run test.load.yaml

      - name: Upload Artillery report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-report
          path: ./artillery-report.json